// <auto-generated />
using System;
using FencingTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FencingTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("FencingTracker.Api.Models.Bout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeftFencerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LeftRedCards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeftScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeftYellowCards")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RightFencerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RightRedCards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RightScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RightYellowCards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeRemainingSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TimeRunning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weapon")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bouts");
                });
#pragma warning restore 612, 618
        }
    }
}
